drupalHashSalt: "su6nfMFns6BNmxKFCAgpiwhgZM"

# Domene som brukes:
ingress:
  hostname: "test2.prototyp.io"
  enabled: true

project:
  repository: "git@github.com:andeersg/k8s-test2.git"
  branch: "main"

# Annoteringene er for let's encrypt.
